---
- name: init aws instances
  hosts: lhost
  connection: local

  tasks:
    - name:  create AWS security group
      ec2_group:
        name: "ansible-sec-group"
        description: "SG"
        region: "eu-central-1"
        rules:
          - proto: "tcp"
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"    
          - proto: "tcp"
            from_port: 80
            to_port: 80
            cidr_ip: "0.0.0.0/0"       
        rules_egress:
          - proto: "all"
            cidr_ip: "0.0.0.0/0"
      register: secgrp

    - name: generate key
      ec2_key:
        name: my_aws_key
        region: "eu-central-1"
      register: ec2_key_result

    - name: save key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="./my_aws_key.pem" mode=0600
      when: ec2_key_result.changed
    
    - name: Create subnet for servers
      ec2_vpc_subnet:
        state: present
        cidr: 10.0.1.16/28
        tags:
          Name: My Subnet
      register: my_subnet
  
    - name: create AWS ec2 instance
      ec2:
        key_name: "my_aws_key"
        group: "ansible-sec-group"
        instance_type: "t2.micro"
        ec2_region: "eu-central-1"
        image: "ami-0fefc541a9298d8c0"
        wait: yes
        count: 1
        vpc_subnet_id: vpc-123456
        assign_public_ip: yes
      register: ec2