---
- name: build AWS instances
  hosts: lhost
  connection: local

  vars:
    mregion: eu-central-1
    mkey_name: my_aws_key3
    mkey: ./my_aws_key.pem
    msecurity_group: test_sec_1
    mimage_ami: ami-092391a11f8aa4b7b

  tasks:
    - name:  create AWS security group
      ec2_group:
        name: "{{ msecurity_group }}"
        description: "SG"
        region: "{{ mregion }}"
        rules:
          - proto: "tcp"
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"    
          - proto: "tcp"
            from_port: 8080
            to_port: 8080
            cidr_ip: "0.0.0.0/0"       
        rules_egress:
          - proto: "all"
            cidr_ip: "0.0.0.0/0"
      register: secgrp

    - name: generate key
      ec2_key:
        name: "{{ mkey_name }}"
        region: "{{ mregion }}"
      register: ec2_key_result

    - name: save key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="{{ mkey }}" mode=0600 force="yes"
      when: ec2_key_result.changed
    
    - name: create 2 AWS ec2 instance
      ec2:
        key_name: "{{ mkey_name }}"
        group: "{{ msecurity_group }}"
        instance_type: "t2.micro"
        ec2_region: "{{ mregion }}"
        image: "ami-092391a11f8aa4b7b"
        wait: yes
        count: 2
        vpc_subnet_id: subnet-1109d95d
        assign_public_ip: yes      
      register: myec2
    
    - name: Add new BUILD instance to host group build
      add_host:
        hostname: "{{ myec2.instances[0].public_ip }}"
        groupname: build

    - name: Add new WEB instance to host group web
      add_host:
        hostname: "{{ myec2.instances[1].public_ip}}"
        groupname: web
      
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 50
        timeout: 400   
        sleep: 50     
        state: started
      with_items: "{{ myec2.instances }}"

    - name: install python on build
      command: "ssh -o 'StrictHostKeyChecking=no' ubuntu@{{ myec2.instances[0].public_ip }} -i ./my_aws_key.pem 'sudo apt update ; sudo apt install -y python ;'"

    - name: install python on web
      command: "ssh -o 'StrictHostKeyChecking=no' ubuntu@{{ myec2.instances[1].public_ip }} -i ./my_aws_key.pem 'sudo apt update ; sudo apt install -y python ;'"   

- name: build war
  hosts: build
  become: yes
  remote_user: ubuntu

  vars:
    ansible_ssh_private_key_file: "{{ mkey }}"
  
  tasks:
    - name: update apt cache
      apt: update_cache=true

    - name: Install packages
      apt: pkg={{ item }} state=latest
      with_items:
        - default-jdk
        - maven
        - git

    - name: clone boxfuse
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse-sample-java-war-hello
      tags: deploy
   
    - name: package boxfuse war
      command: mvn package -f /home/boxfuse-sample-java-war-hello

    - name: Copy WAR
      fetch:
        src: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: ./hello-1.0.war
        flat: true

- name: deploy to web instance
  hosts: web 
  become: yes
  remote_user: ubuntu

  vars:
    ansible_ssh_private_key_file: "{{ mkey }}"
    
  tasks:
    - name: ensure tomcat package is present
      apt: pkg=tomcat8 state=latest update_cache=yes
      
    - name: Copy WAR
      copy:
        src: ./hello-1.0.war
        dest: /var/lib/tomcat8/webapps/hello-1.0.war